#!/usr/bin/env ruby
#
# https://github.com/SteveKChiu/ios-res-tool
#
# Copyright 2015, Steve K. Chiu <steve.k.chiu@gmail.com>
#
# What it does is to scan iOS resources and generate R+assets.swift for
# .xcassets catalog
#
# The MIT License (http://www.opensource.org/licenses/mit-license.php)
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

require 'fileutils'
require 'pathname'
require 'optparse'

ARGV << '--help' if ARGV.empty?

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: ios-assets.rb [options]"

  opts.on("--res=IOS_RES_DIR", "directory for iOS resources") do |v|
    options[:res] = v
  end

  opts.on_tail("--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

res_path = Pathname.new(File.expand_path(options[:res])) if options[:res]

unless res_path
  puts "Error! resource directory not specified"
  exit
end

unless res_path.exist?
  puts "Error! resource directory not found: #{res_path}"
  exit
end

imageset_keys = {}
spriteatlas_keys = {}
dataset_keys = {}

Pathname.glob(res_path + '*.xcassets/').each { |assets_path|
  Pathname.glob(assets_path + "**/*.imageset/").each { |imageset_path|
    key = imageset_path.basename.to_s.gsub(/^(.*)\.imageset$/, '\1')
    imageset_keys[key] = true
  }

  Pathname.glob(assets_path + "**/*.spriteatlas/").each { |spriteatlas_path|
    key = spriteatlas_path.basename.to_s.gsub(/^(.*)\.spriteatlas$/, '\1')
    spriteatlas_keys[key] = true
  }

  Pathname.glob(assets_path + "**/*.dataset/").each { |dataset_path|
    key = dataset_path.basename.to_s.gsub(/^(.*)\.dataset$/, '\1')
    dataset_keys[key] = true
  }
}

imageset_keys = imageset_keys.keys.sort
spriteatlas_keys = spriteatlas_keys.keys.sort
dataset_keys = dataset_keys.keys.sort

swift_path = res_path + "R+assets.swift"
swift_path.delete if swift_path.exist?

File.open(swift_path, 'wb') { |f|
  f.write "// THIS FILE IS GENERATED BY TOOL, PLEASE DO NOT EDIT!\n\n"
  f.write "import UIKit\n"

  if not spriteatlas_keys.empty?
    f.write "import SpriteKit\n"
  end

  f.write "\n"

  f.write "extension R {\n\n"

  if not imageset_keys.empty?
    f.write "    enum image : String {\n"
    imageset_keys.each { |key|
      f.write "        case #{key}\n"
    }
    f.write "    }\n\n"
  end

  if not spriteatlas_keys.empty?
    f.write "    enum atlas : String {\n"
    spriteatlas_keys.each { |key|
      f.write "        case #{key}\n"
    }
    f.write "    }\n\n"
  end

  if not dataset_keys.empty?
    f.write "    enum data : String {\n"
    dataset_keys.each { |key|
      f.write "        case #{key}\n"
    }
    f.write "    }\n\n"
  end

  f.write "}\n\n"

  if not imageset_keys.empty? or not spriteatlas_keys.empty? or not dataset_keys.empty?
    f.write "postfix operator ^ {}\n\n"
  end

  if not imageset_keys.empty?
    f.write "postfix func ^ (key: R.image) -> UIImage {\n"
    f.write "    return UIImage(named: key.rawValue)!\n"
    f.write "}\n\n"
    puts "#{imageset_keys.size} imageset found"
  end

  if not spriteatlas_keys.empty?
    f.write "postfix func ^ (key: R.atlas) -> SKTextureAtlas {\n"
    f.write "    return SKTextureAtlas(named: key.rawValue)!\n"
    f.write "}\n\n"
    puts "#{spriteatlas_keys.size} spriteatlas found"
  end

}
